runtime: python39

service: default

handlers:
- url: /
  static_files: dynamic-page/index.html
  upload: dynamic-page/index.html


- url: /css
  static_dir: dynamic-page/css

- url: /js
  static_dir: dynamic-page/js

- url: /img
  static_dir: dynamic-page/img

- url: /.*
  static_dir: dynamic-page


- url: /.*
  secure: always
  redirect_http_response_code: 302
  script: auto